import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Header from '../components/header/Header'
import TokenList from '../components/lists/TokenList'
import { apiAddToken, apiGetTokens } from './api/api'

const Home: NextPage = () => {

  const [tokens, setTokens] = useState<any>([]);
  const [contract, setContract] = useState<string>('');

  useEffect(() => {
    apiGetTokens().then((response) => {
      setTokens(response);
    });
  }, [])

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setContract(event.target.value);
  } 

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    const token: any = await apiAddToken(contract);
    if (token) {
      setTokens([...tokens, token]);
    } else {
      alert('Something went wrong. Try again');
    }
  }
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        { tokens && <TokenList tokens={tokens}/>}
        <form onSubmit={handleSubmit}>
          <input type="text" placeholder="Contract" onChange={handleChange}/>
          <button type="submit">Add Token</button>
        </form>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
